import assert from 'node:assert/strict'
export default async function(page) {
  await page.waitForFunction(()=>window.__THREEDPISO_QA__?.snapshot().loaded)
  const state=()=>page.evaluate(()=>window.__THREEDPISO_QA__.snapshot())
  const project=point=>page.evaluate(p=>window.__THREEDPISO_QA__.project(p),point)
  const wait=()=>page.waitForTimeout(350)
  const world=await page.evaluate(()=>fetch('/models/world.json').then(r=>r.json()))
  const checks=[]
  assert.ok((await state()).calls>20,'GLB must be drawn, not only loaded')
  await page.screenshot({path:'../logs/web_desktop.png'})
  checks.push('seven GLB assets visible')
  await page.getByRole('button',{name:'Planta',exact:true}).click();await wait()
  assert.equal((await state()).mode,'plan')
  await page.screenshot({path:'../logs/web_planta.png'})
  const sofa=world.furniture.find(f=>f.id==='Sofa_Main')
  const p=await project([sofa.position[0],.85,sofa.position[2]])
  await page.mouse.click(p.x,p.y);await wait()
  assert.equal((await state()).selected,'Sofa_Main','raycast selects sofa')
  const original=(await state()).furnitureVisible
  await page.getByRole('button',{name:'Ocultar este mueble'}).click();await wait()
  assert.equal((await state()).furnitureVisible,original-1)
  assert.ok(!(await page.evaluate(()=>window.__THREEDPISO_QA__.visibleObjects())).includes('Sofa_Main'))
  await page.getByRole('button',{name:'Ocultar todo',exact:true}).click();await wait()
  assert.equal((await state()).furnitureVisible,0)
  const visible=await page.evaluate(()=>window.__THREEDPISO_QA__.visibleObjects())
  assert.ok(visible.some(n=>n.startsWith('Architecture_WALLS')||n.startsWith('Wall_')))
  await page.getByRole('button',{name:'Mostrar todo',exact:true}).click();await wait()
  assert.equal((await state()).furnitureVisible,original)
  checks.push('selection, individual hide, groups and architecture preservation')
  await page.getByRole('checkbox',{name:'Salón',exact:true}).uncheck();await wait()
  assert.ok((await state()).furnitureVisible<original)
  await page.getByRole('checkbox',{name:'Salón',exact:true}).check()
  await page.getByRole('button',{name:'Medir',exact:true}).click()
  const start=world.rooms.find(r=>r.id==='hallway').spawn
  for(const x of [start[0]-.8,start[0]+.2]){
    const screen=await project([x,.012,start[1]])
    await page.mouse.click(screen.x,screen.y);await wait()
  }
  const pts=(await state()).points;assert.equal(pts.length,2)
  const distance=Math.hypot(...pts[0].map((v,i)=>v-pts[1][i]))
  assert.ok(Math.abs(distance-1)<.03,`raycast metric check: ${distance}`)
  await page.screenshot({path:'../logs/web_medicion.png'})
  await page.getByRole('button',{name:'Terminar medición'}).click()
  checks.push(`real raycast measurement ${distance.toFixed(3)}m for 1m reference`)
  await page.getByRole('checkbox',{name:'Mostrar medidas',exact:true}).check()
  assert.ok(await page.locator('.room-label').count()>=9)
  await page.getByRole('checkbox',{name:'Mostrar medidas',exact:true}).uncheck()
  for(const id of ['entry','kitchen',...world.rooms.map(r=>r.id)]){
    await page.getByLabel('Elegir estancia').selectOption(id);await wait()
    const actual=await state(),target=id==='entry'?world.entry:id==='kitchen'?world.kitchenSpawn:world.rooms.find(r=>r.id===id).spawn
    assert.equal(actual.mode,'walk');assert.ok(Math.abs(actual.eyeHeight-1.7)<.001)
    assert.ok(Math.hypot(actual.position[0]-target[0],actual.position[1]-target[1])<.01)
  }
  checks.push('all rooms, kitchen, bathrooms and terrace teleports at eye height 1.70m')
  await page.getByRole('button',{name:'Volver a entrada'}).click();await wait()
  const initial=await state()
  await page.getByRole('button',{name:'Entrar en recorrido'}).click()
  await page.waitForFunction(()=>!!document.pointerLockElement && window.__THREEDPISO_QA__?.snapshot().locked)
  await page.keyboard.down('w');await page.waitForTimeout(1300);await page.keyboard.up('w');await wait()
  const moved=await state()
  assert.ok(Math.hypot(moved.position[0]-initial.position[0],moved.position[1]-initial.position[1])>.15,'W moves human camera '+JSON.stringify({initial,moved}))
  await page.keyboard.down('a');await page.waitForTimeout(1600);await page.keyboard.up('a');await wait()
  const stopped=await state()
  const right=Math.max(...world.outer.map(p=>p[0]))
  assert.ok(stopped.position[0]<right-.2,'solid facade blocks movement')
  await page.mouse.move(900,450);await wait()
  await page.keyboard.press('Escape');await wait()
  assert.equal((await state()).locked,false)
  checks.push('PointerLock, WASD movement, solid wall collision and ESC release')
  await page.getByLabel('Elegir estancia').selectOption('living-room');await wait()
  await page.screenshot({path:'../logs/web_recorrido.png'})
  await page.getByRole('button',{name:'Vista general',exact:true}).click();await wait()
  assert.equal((await state()).mode,'overview')
  const canvas=await page.locator('canvas').boundingBox()
  const before=(await state()).camera
  await page.mouse.move(canvas.x+canvas.width*.5,canvas.y+canvas.height*.5);await page.mouse.down();await page.mouse.move(canvas.x+canvas.width*.6,canvas.y+canvas.height*.5,{steps:8});await page.mouse.up();await wait()
  assert.ok((await state()).camera.some((v,i)=>Math.abs(v-before[i])>.1))
  checks.push('orbit rotation and plan mode')
  const mobileContext=await page.context().browser().newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1})
  const mobile=await mobileContext.newPage(),mobileErrors=[]
  mobile.on('pageerror',e=>mobileErrors.push(String(e)))
  await mobile.goto('http://127.0.0.1:5173/');await mobile.waitForFunction(()=>window.__THREEDPISO_QA__?.snapshot().loaded)
  await mobile.getByRole('button',{name:'Abrir panel'}).click()
  await mobile.getByLabel('Elegir estancia').selectOption('entry')
  await mobile.getByRole('button',{name:'Plegar panel'}).click();await mobile.waitForTimeout(500)
  const mobState=()=>mobile.evaluate(()=>window.__THREEDPISO_QA__.snapshot())
  const mbefore=await mobState(),j=await mobile.getByRole('application',{name:'Joystick para caminar'}).boundingBox()
  const cdp=await mobile.context().newCDPSession(mobile)
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:j.x+j.width/2,y:j.y+j.height/2}]})
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:j.x+j.width/2,y:j.y+12}]})
  await mobile.waitForTimeout(1500)
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
  const mafter=await mobState()
  assert.ok(Math.hypot(mafter.position[0]-mbefore.position[0],mafter.position[1]-mbefore.position[1])>.1,'touch joystick moves')
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:190,y:410}]})
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:240,y:410}]})
  await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]})
  await mobile.waitForTimeout(400)
  assert.ok(Math.abs((await mobState()).yaw-mafter.yaw)>.05,'touch drag looks')
  assert.ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))
  await mobile.screenshot({path:'../logs/web_mobile.png'})
  assert.deepEqual(mobileErrors,[])
  await mobileContext.close()
  checks.push('390px mobile layout, room selector, joystick and touch look')
  return {checks,measurement:distance,metrics:await state()}
}
